name: Send email

on:
  workflow_dispatch:
jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v7
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          # Optional (recommended) mail server username:
          #username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          #password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # Required recipients' addresses:
          to: ${{secrets.MAIL_TO}}
          # Required sender full name (address can be skipped):
          from: ${{secrets.MAIL_FROM}}
          # Optional plain body:
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # Optional HTML body read from file:
          #html_body: file://README.html
          # Optional carbon copy recipients:
          #cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          #bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          #reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          #in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          #ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          #attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          #priority: low
          # Optional nodemailerlog: true/false
          nodemailerlog: true
          # Optional nodemailerdebug: true/false if true lognodem will also be set true
          nodemailerdebug: true
          # Optional custom SMTP MAIL FROM address (overrides username):
          #envelope_from: mailer@example.com
          # Optional custom SMTP RCPT TO addresses (overrides to, cc, bcc):
          #envelope_to: mailer@example.com,admin@example.com
